### ISSUE TITLE
Contract Wallet Sent to Incorrect Address?

### ISSUE THREAD

**Issue by PatrickOBTC** [ethereum/meteor-dapp-wallet#62]
I recently attempted to send a transaction from the GUI wallet. The Ether is gone but it did not wind up at the intended destination.

The transaction appears correct in my wallet's list of transactions. However, when I check the transaction on Etherscan.io, my address is shown as the "to" address and the address I intended to transfer my Ether to is not correct at all. The intended destination does show up as part of the "input data" though.

TX: https://etherscan.io/tx/0x08dfb53c07ddd741e7674090306647e1d5d333282f3a7b4fc59f2dd261be640e

My Address: 0x2761c0ad62d0f7f96f38332cabb9229378c9bfc9

Intended Destination: 8f28be6335a844162bedeed8002ee76fb1c08af9

This in on a Win8 install from a "contract based wallet" not an "account"

Did I make a mistake or was this a bug?

BTW I do have an Ubuntu based install of Geth and I am not afraid of the CLI if that might be able to help yield some useful data about what went wrong.

Any insight or help is appreciated. Thanks.

**Comment by frozeman** [comment]
This is actually correct.
The reason why the tx doesn't look like a normal value transfer is because you *instruct* the wallet to move money for you, so the value and the destination address is in the instruction:
```
0xb61d27f60000000000000000000000008f28be6335a844162bedeed8002ee76fb1c08af9000000000000000000000000000000000000000000000002fb474098f67c0000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
- `b61d27f6` This is the function name to call
- `8f28be6335a844162bedeed8002ee76fb1c08af9` this is the first param, you destination address
- `2fb474098f67c00` this is the value  you wanted to transfer (maybe 2 zeros more) in wei.

So the money should showed up in the destination address, right?

**Comment by PatrickOBTC** [comment]
Thank you for your reply. I can see that the value actually did arrive in the destination wallet. It does not show up in the transactions received list on either etherscan.io or etherchain.org and that's what confused me.

**Comment by frozeman** [comment]
thanks.

wallet transfers are not showing up as tx, as they are not tx :)
They are messages, which are not visible in block explorers. You have to out you bitcoin hat away in ethereum...
The important things are logs, not plain tx
